<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>RefuseKat</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>693ae4ff-1258-4ec5-98a0-ab8d56cfe4eb</testSuiteGuid>
   <testCaseLink>
      <guid>3c3a1da7-63d2-4c09-b37d-e916c4e380cd</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Basics/Login</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b94cf292-e2fc-4d9c-9da6-268785749709</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e2fef3b7-b66e-484f-a03f-040074d90034</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>cee65260-b3b2-4a06-b7d7-ae9c3137a3b9</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/RefuseAllKat</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>92f6b5a4-7b45-420b-884b-a8cbd4aef6b2</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>2771d6c1-dc34-4a9d-9aa9-66836611d268</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Basics/Logout</testCaseId>
   </testCaseLink>
</TestSuiteEntity>
