<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Kategorisierung</name>
   <tag></tag>
   <elementGuidId>b4d9ee8f-19cc-41b5-a9e6-476a5f8ba18d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;Kategorisierung2&quot;)/span[1][count(. | //span[(text() = 'Kategorisierung' or . = 'Kategorisierung')]) = count(//span[(text() = 'Kategorisierung' or . = 'Kategorisierung')])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Kategorisierung</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Kategorisierung2&quot;)/span[1]</value>
   </webElementProperties>
</WebElementEntity>
